"use client";

import * as React from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { Home, ArrowRight, Filter, CheckCircle2, Clock, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { PublicLayout } from "@/components/layout/PublicLayout";
import { Button, Card, CardContent, Badge } from "@/components/ui";
import { mockProjects, type Project } from "@/lib/api/mock-db";

const allStyles = Array.from(new Set(mockProjects.filter((p) => p.style).map((p) => p.style)));

const styleMap: Record<string, string> = {
  Modern: "bg-blue-100 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400",
  Contemporary: "bg-purple-100 dark:bg-purple-900/20 text-purple-600 dark:text-purple-400",
  Scandinavian: "bg-green-100 dark:bg-green-900/20 text-green-600 dark:text-green-400",
  Mediterranean: "bg-amber-100 dark:bg-amber-900/20 text-amber-600 dark:text-amber-400",
};

const statusConfig: Record<string, { label: string; variant: "success" | "warning" | "info" | "default" }> = {
  completed: { label: "Completed", variant: "success" },
  draft: { label: "Draft", variant: "warning" },
  generating: { label: "Generating", variant: "info" },
};

export default function ShowcasePage() {
  const [activeStyle, setActiveStyle] = React.useState<string | null>(null);

  const filtered = activeStyle
    ? mockProjects.filter((p) => p.style === activeStyle)
    : mockProjects;

  return (
    <PublicLayout>
      <div className="min-h-screen pt-24 pb-16">
        <div className="container mx-auto max-w-6xl px-4 md:px-8">
          {/* Hero */}
          <div className="text-center max-w-3xl mx-auto mb-12">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
              <Badge variant="info" className="mb-4">Showcase</Badge>
              <h1 className="text-4xl md:text-5xl font-bold mb-4">Project Showcase</h1>
              <p className="text-lg text-slate-500 dark:text-slate-400">
                Explore beautiful homes and layouts generated by the PlanCraftAI engine.
              </p>
            </motion.div>
          </div>

          {/* Filters */}
          <div className="flex flex-wrap items-center gap-3 mb-8">
            <div className="flex items-center gap-2 mr-2">
              <Filter className="w-4 h-4 text-slate-500" />
              <span className="text-sm font-medium text-slate-500">Style:</span>
            </div>
            <button
              onClick={() => setActiveStyle(null)}
              className={cn(
                "px-4 py-2 rounded-xl text-sm font-semibold transition-all",
                !activeStyle
                  ? "bg-primary text-white shadow-md"
                  : "glass-card dark:glass-card-dark hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-600 dark:text-slate-300"
              )}
            >
              All
            </button>
            {allStyles.map((style) => (
              <button
                key={style}
                onClick={() => setActiveStyle(style)}
                className={cn(
                  "px-4 py-2 rounded-xl text-sm font-semibold transition-all",
                  activeStyle === style
                    ? "bg-primary text-white shadow-md"
                    : "glass-card dark:glass-card-dark hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-600 dark:text-slate-300"
                )}
              >
                {style}
              </button>
            ))}
          </div>

          {/* Grid */}
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
            {filtered.map((project, i) => (
              <motion.div
                key={project.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: i * 0.05 }}
              >
                <ProjectCard project={project} />
              </motion.div>
            ))}
          </div>

          {/* Empty state */}
          {filtered.length === 0 && (
            <div className="text-center py-16">
              <Home className="w-12 h-12 text-slate-300 mx-auto mb-4" />
              <h3 className="text-xl font-bold text-slate-500 mb-2">No projects found</h3>
              <p className="text-slate-400 mb-4">No projects match this style filter.</p>
              <Button variant="secondary" onClick={() => setActiveStyle(null)}>Clear Filter</Button>
            </div>
          )}

          {/* CTA */}
          <div className="text-center">
            <Card className="max-w-xl mx-auto">
              <CardContent className="py-8">
                <h2 className="text-xl font-bold mb-2">Want to see more?</h2>
                <p className="text-sm text-slate-500 dark:text-slate-400 mb-4">Browse our full gallery with detailed project information.</p>
                <Link href="/gallery">
                  <Button>
                    View Full Gallery
                    <ArrowRight className="w-4 h-4 ml-2" />
                  </Button>
                </Link>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
}

function ProjectCard({ project }: { project: Project }) {
  const status = statusConfig[project.status] || statusConfig.draft;
  const statusIcon = project.status === "completed" ? <CheckCircle2 className="w-3.5 h-3.5" />
    : project.status === "generating" ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
    : <Clock className="w-3.5 h-3.5" />;

  return (
    <Card className="group overflow-hidden hover:shadow-xl transition-all hover:border-primary/30">
      <div className="aspect-video bg-slate-200 dark:bg-slate-800 relative overflow-hidden">
        <div className="absolute inset-0 flex items-center justify-center text-slate-400">
          <Home className="w-12 h-12 opacity-20" />
        </div>
        <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-end p-4">
          <span className="text-white text-sm font-medium">View Project Details</span>
        </div>
        {project.status === "generating" && (
          <div className="absolute top-3 right-3">
            <Badge variant="info">
              <Loader2 className="w-3 h-3 animate-spin mr-1" />
              Generating
            </Badge>
          </div>
        )}
      </div>
      <CardContent>
        <div className="flex items-start justify-between mb-3">
          <h3 className="font-bold text-lg">{project.name}</h3>
          <Badge variant={status.variant}>
            {statusIcon}
            <span className="ml-1">{status.label}</span>
          </Badge>
        </div>
        <p className="text-sm text-slate-500 dark:text-slate-400 mb-4 line-clamp-2">{project.description}</p>
        <div className="flex flex-wrap gap-2 mb-4">
          {project.plotLength > 0 && (
            <span className="px-2.5 py-1 text-xs font-medium bg-slate-100 dark:bg-slate-800 rounded-md text-slate-600 dark:text-slate-300">
              {project.plotLength}&times;{project.plotWidth} ft
            </span>
          )}
          <span className="px-2.5 py-1 text-xs font-medium bg-slate-100 dark:bg-slate-800 rounded-md text-slate-600 dark:text-slate-300">
            {project.floors} Floor{project.floors > 1 ? "s" : ""}
          </span>
          <span className="px-2.5 py-1 text-xs font-medium bg-slate-100 dark:bg-slate-800 rounded-md text-slate-600 dark:text-slate-300">
            {project.rooms.length} Rooms
          </span>
          {project.style && (
            <span className={cn("px-2.5 py-1 text-xs font-medium rounded-md", styleMap[project.style] || "")}>
              {project.style}
            </span>
          )}
        </div>
        {project.costEstimate && (
          <div className="pt-3 border-t border-slate-200 dark:border-slate-800">
            <span className="text-sm text-slate-500">Est. Cost: </span>
            <span className="text-sm font-bold">${project.costEstimate.total.toLocaleString()}</span>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
