"""
Blueprint Renderer - Generates PDF blueprints with technical details.
"""
import os
import logging

logger = logging.getLogger(__name__)


class BlueprintRenderer:
    def render_pdf(self, project, rooms, output_path: str):
        try:
            from reportlab.lib.pagesizes import letter, A4
            from reportlab.lib.units import inch
            from reportlab.pdfgen import canvas
            from reportlab.lib import colors
        except ImportError:
            logger.warning("reportlab not available, skipping PDF render")
            return
        
        width, height = A4
        c = canvas.Canvas(output_path, pagesize=A4)
        
        # Title
        c.setFont("Helvetica-Bold", 20)
        c.drawString(50, height - 50, f"PlanCraftAI - Blueprint")
        
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 80, f"Project: {project.name}")
        c.drawString(50, height - 100, f"Plot: {project.plot_width}' x {project.plot_length}'")
        c.drawString(50, height - 120, f"Facing: {project.facing}")
        c.drawString(50, height - 140, f"Style: {project.style}")
        
        # Room table
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, height - 180, "Room Schedule")
        
        y_pos = height - 210
        c.setFont("Helvetica-Bold", 10)
        c.drawString(50, y_pos, "Room Name")
        c.drawString(200, y_pos, "Width")
        c.drawString(280, y_pos, "Length")
        c.drawString(360, y_pos, "Area")
        c.drawString(440, y_pos, "Level")
        
        y_pos -= 20
        c.setFont("Helvetica", 10)
        
        for room in rooms:
            c.drawString(50, y_pos, room.name)
            c.drawString(200, y_pos, f"{room.width}'")
            c.drawString(280, y_pos, f"{room.length}'")
            c.drawString(360, y_pos, f"{room.width * room.length} sqft")
            c.drawString(440, y_pos, str(room.level))
            y_pos -= 16
            if y_pos < 50:
                c.showPage()
                y_pos = height - 50
        
        # Floor plan sketch
        scale = 2.0
        margin = 50
        px = margin
        py = 100
        pw = project.plot_width * scale
        ph = project.plot_length * scale
        
        c.setStrokeColor(colors.black)
        c.setLineWidth(2)
        c.rect(px, py, pw, ph)
        
        for room in rooms:
            rx = px + room.x * scale
            ry = py + room.y * scale
            rw = room.width * scale
            rh = room.length * scale
            c.setLineWidth(1)
            c.setStrokeColor(colors.gray)
            c.rect(rx, ry, rw, rh)
            c.setFont("Helvetica", 7)
            c.drawString(rx + 2, ry + 2, room.name[:15])
        
        # Footer
        c.setFont("Helvetica", 8)
        c.drawString(50, 30, "Generated by PlanCraftAI - All dimensions in feet")
        c.drawString(400, 30, "Scale: Not to scale")
        
        c.save()
